car/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'', include('controller.urls', namespace='controller')),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'tinymce/', include('tinymce.urls')),
)

controller/urls.py
from django.conf.urls import patterns, url
from controller import views
from controller.forms import LoginForm
from django.contrib.auth.decorators import login_required
urlpatterns = patterns('',
    url(r'^$', login_required(views.PermisionView.as_view()), name='permission'),
    url(r'login', 'django.contrib.auth.views.login', {
                                'template_name': 'controller/logon.html',
                                'authentication_form': LoginForm,}, name='login'),
    url(r'logout', 'django.contrib.auth.views.logout', {'next_page': 'login'}, name='logout'),
    url(r'register', views.Register.as_view(template_name='controller/registration.html')),
    url(r'news$', views.NewsView.as_view(),name='news'),
    url(r'feedback$', views.FeedBack.as_view(), name='feedback'),
    url(r'map$', views.historyMap, name='mongolia'),
    url(r'back/(?P<pk>\d+)$', views.BackView.as_view(), name='back'),
    url(r'front$', views.frnt, name='front'),
    url(r'reserve',
        login_required(views.Res.as_view(template_name='controller/reservation.html')),name='reservation'),

)

controller/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


insert = models.BooleanField(default=True)
insert.contribute_to_class(User, 'INSERT')
update = models.BooleanField(default=True)
update.contribute_to_class(User, 'UPDATE')
delete = models.BooleanField(default=True)
delete.contribute_to_class(User, 'DELETE')
drop  = models.BooleanField(default=True)
drop.contribute_to_class(User, 'DROP')
create = models.BooleanField(default=True)
create.contribute_to_class(User, 'CREATE')


class employers(models.Model):
    lname = models.CharField(max_length=20, db_index=True)
    fname = models.CharField(max_length=20, db_index=True)
    address = models.CharField(max_length=20, db_index=True)
    salary = models.IntegerField()
    TYPE_CHOICES = (
        (0, ' Motor Driver '),
        (1, ' Admin '),
    )
    position = models.PositiveIntegerField(
        choices=TYPE_CHOICES,
        null=False
    )
    registered_at = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return unicode(self.lname)


class car(models.Model):
    number = models.CharField(max_length=6)
    onOff = models.BooleanField(default=False)
    employer = models.ForeignKey(employers)
    
    def __unicode__(self):
        return unicode(self.number)

class District(models.Model):
    name = models.CharField(max_length=20)
    
    def __unicode__(self):
        return unicode(self.name)


class reservation(models.Model):
    name = models.CharField(max_length=40,null=False)
    mobile = models.IntegerField(null=False)
    home_number = models.IntegerField(null=False)
    district = models.ForeignKey(District)
    command = models.PositiveIntegerField(null=False)
    position = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return unicode(self.name)


class pay(models.Model):
    mission = models.BooleanField(default=True)
    take = models.IntegerField(db_index=True)
    car = models.ForeignKey(car)
    time = models.DateTimeField()
    
    def __unicode__(self):
        return unicode(self.car)

class News(models.Model):
    header = models.CharField(max_length=255)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return unicode(self.header)

class Feedback(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return "feedback "+unicode(self.id)
    
    def save(self, *args, **kwargs):
        import logging
        logging.error(args)    
        super(Feedback, self).save(*args, **kwargs)


class back(models.Model):
    cont = models.TextField()
    name = models.CharField(max_length=255)


class front(models.Model):
    cont = models.TextField()

#class Million(models.Model):
#    name = models.TextField()
#    date = models.DateTimeField(auto_now_add=True)
#    dec = models.IntegerField()
#    flt = models.FloatField()
#
    

# Create your models here.

controller/forms.py
# coding: utf-8
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.flatpages.models import FlatPage
from tinymce.widgets import TinyMCE
from controller.models import reservation
import datetime
en_mn = {
    'username': 'Нэвтрэх нэр',
    'first_name': 'Нэр',
    'last_name': 'Овог',
    'password': 'Нууц үг',
    'password1': 'Нууц үг',
    'password2': 'Нууц үг',
    'email': 'Email хаяг',
}

class UserForm(UserCreationForm):
    class Meta:
        attrs = {'class': 'form-control'}
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')

        widgets = {
                'email': forms.TextInput(attrs=attrs),
                'first_name': forms.TextInput(attrs=attrs),
                'last_name': forms.TextInput(attrs=attrs),
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for field in ['username', 'password1', 'password2']:
            self.fields[field].widget.attrs = {'class': 'form-control'}

        for field in ['email', 'first_name', 'last_name']:
            self.fields[field].required = True

        for field in UserForm._meta.fields:
            self.fields[field].label = en_mn[field]



class SuperUserForm(forms.Form):
    CREATE  = forms.BooleanField(required=False)
    DROP = forms.BooleanField(required=False)
    INSERT  = forms.BooleanField(required=False)
    UPDATE  = forms.BooleanField(required=False)
    DELETE  = forms.BooleanField(required=False)
    
    def clean(self):
        cd = super(SuperUserForm, self).clean()
        return cd
    
    def save(self, user):
        cd = self.cleaned_data
        for key, data in cd.items():
            if data:
                if key == 'INSERT':
                    user.INSERT = True
                if key == 'DELETE':
                    user.DELETE = True
                if key == 'UPDATE':
                    user.UPDATE = True
                if key == 'DROP':
                    user.DROP = True
                if key == 'CREATE':
                    user.CREATE = True
            else:
                if key == 'INSERT':
                    user.INSERT = False
                if key == 'DELETE':
                    user.DELETE = False
                if key == 'UPDATE':
                    user.UPDATE = False
                if key == 'DROP':
                    user.DROP = False
                if key == 'CREATE':
                    user.CREATE = False
        user.save() 

class LoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': 'Таны Нэр эсвэл Нууц үг буруу байна.',
        'inactive': 'Таны нэвтрэх эрх цуцлагдсан байна.'
    }

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        for field in ['username', 'password']:
            self.fields[field].widget.attrs = {'class': 'form-control'}

        for field in ['username', 'password']:
            self.fields[field].label = en_mn[field]


class FlatPageForm(forms.ModelForm):
    class Meta:
        model = FlatPage


class ReservationForm(forms.Form):
    position = forms.CharField()
    created_at = forms.DateTimeField(initial=datetime.datetime.now)
    
    def save(self):
        Reservation = reservation()
        Reservation.position = self.cleaned_data.get('position', None)
        #Reservation.client = self.cleaned_data.get('client_id', None) 
        #Reservation.created_at = self.cleaned_data.get('created_at', None)
        Reservation.save()
        return reservation

# class LoginForm(forms.Form):
#     username = forms.CharField(required=True,
#             widget=forms.TextInput(attrs={'class': 'form-control'}))
#     password = forms.CharField(
#             widget=forms.PasswordInput(attrs={'class': 'form-control'}))

controller/views.py
# Create your views here.
from django.views import generic
from controller.forms import SuperUserForm, ReservationForm 
from django.shortcuts import redirect, render
from controller.models import  News
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import mail_admins
from controller.models import reservation, Feedback, back, front


class NewsView(generic.ListView):
    template_name = 'controller/news.html'
    def get_queryset(self):
        return News.objects.all()
    def get_context_data(self, **kwargs):
        context = super(NewsView, self).get_context_data(**kwargs)
        context.update ({
            'news': News.objects.all(),
        })
        return context


class PermisionView(generic.ListView):
    template_name = 'controller/index.html'
    def get_queryset(self):
        return Feedback.objects.all()
    def get_context_data(self, **kwargs):
        context = super(PermisionView, self).get_context_data(**kwargs)
        context.update ({
            'form': SuperUserForm(),
        })
        return context

@login_required
def change_permission(request):
    form = SuperUserForm(request.POST)
    if form.is_valid():
        form.save(request.user)
    return redirect("controller:permission")

class Register(CreateView):
    form_class = UserForm
    model = User
    success_url = reverse_lazy('controller:login')
    

class Res(CreateView):
    model = reservation
    template_name = 'controller/reservation.html'
    success_url = reverse_lazy("controller:permission")


class FeedBack(CreateView):
    model = Feedback
    template_name = 'controller/feedback.html'
    success_url = reverse_lazy('controller:permission')
    
    #def form_valid(self,form):
    #    mail_admins('easy taxi', unicode('check feedback'), fail_silently=True)
    #    form.save()
    #    return super(FeedBack, self).form_valid(form) 

class ReservationView(generic.ListView):
    template_name = 'controller/reservation.html'
    
    def get_queryset(self):
        return Feedback.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(ReservationView, self).get_context_data(**kwargs)
        context.update({
            'form': ReservationForm()
        })
        return context

def historyMap(request):
    return render(request, "controller/map.html")



class BackView(generic.DetailView):
    model = back
    template_name = 'controller/back.html'
    
    def get_context_data(self, **kwargs):
        context = super(BackView, self).get_context_data(**kwargs)
        context.update({
            'cont': back.objects.filter(pk=self.object.id)
        })
        return context
   
    def post(self, request, *args, **kwargs):
        front.objects.create(cont=request.POST.get('content'))
        return render(request, 'controller/front.html') 
    

def frnt(request):
    data = front.objects.all().order_by()
    context = {
        'content': data        
    }
    return render(request, "controller/front.html", context)

controller/templates/controller/back.html
{% extends 'controller/base.html' %}
{% block 'Title' %}
    Back
{% endblock %}

{% block 'content' %}

<script>
    $(document).ready(function(){
        $(document).on('click','#send', function(){
            $('#hid').val(data)
            document.forms["myForm"].submit();
        })
    })
</script>
<div class='container'>
        <form action="" method="post" accept-charset="utf-8">
            {% csrf_token %} 
            <textarea rows="10" cols="40" class='form-control'name ='content'>
               {% for one in cont  %}
                {{ one.cont }}
               {% endfor %}
            </textarea>
            <input type="submit" class='btn btn-primary' value='publish'
            id='send' name='btn'/>
        </form>
    </div>
    <div class='container'>
        <a href="1">accordion</a>
        <a href="2">dialog</a>
        <a href="3">tabs</a>
        <a href="4">tooltip</a>
        <a href="5">menu</a>
        <a href="6">slider</a>
    </div>
    <div >
        
{% endblock %}

controller/templates/controller/base.html
<html>
    <head>
        <title> 
            {% block 'Title' %}{% endblock %} 
        </title>
        {% include 'controller/jslink.html' %}
        {% block "somejs" %}
            
        {% endblock %}
    </head>
    <body style="background:url('static/media/bg.jpg')">
        {% include "controller/navbar.html" %}
        
        {% block 'content' %}{% endblock %}
    </body>
</html>

controller/templates/controller/feedback.html
{% extends 'controller/forms.html' %}
{% block 'title' %}
  Feedback
{% endblock %}

{% block 'header' %}
  Feedback  
{% endblock %}

{% block 'sm-type' %}danger{% endblock %}

{% block  'btn-type'%}success{% endblock %}
{% block 'sm-val' %}
  Clear
{% endblock %}
{% block 'bg-val' %}
  Send Data
{% endblock %}

{% block 'warning' %}
    <div class='col-lg-4'>
       <div class="alert alert-dismissable alert-success">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <strong>Холбоо барих</strong></br>
              <p> Утас: 9121126, 95582664</br>
                И-Майл: easytaxi@changes.com
              </p>
        </div> 
    </div>
{% endblock %}

controller/templates/controller/forms.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
    {% load staticfiles %}
    <title>
        {% block 'title' %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/stylesheets/bootstrap.min.css' %}" title="" type="" />
    <script src='{% static 'javascripts/libs/bootstrap.min.js' %}' type='text/javascript' charset='utf-8'></script>
<script src="{% static 'javascripts/libs/jquery.min.js' %}" type='text/javascript' charset='utf-8'></script>
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function(){
          $("input,select,textarea").addClass('form-control');
          $(".btn").removeClass('form-control');
      });
    </script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  </head>
  <body style="background:url('static/media/bgf.png')">
    <div class='container'> 
        <div class='bs-docs-section'>
          <div class='row'>
            <div class='col-lg-12'>
              <div class='page-header'>
                <h1 style="color:white">
                {% block 'header' %}
                {% endblock %}
                </h1>
              </div>
            </div>
          </div>
        </div>
    <div class=''>
      <div class="container well ">
        <div class='row'>
        <div class='col-lg-8'>
          
      <form action='' method='post' class=' bs-example form-horizontal' accept-charset='utf-8'>{% csrf_token %}
        {% for field in form %}
              {{ field.errors }}
              <div class='form-group'>
                <label for='id_{{ field.label|lower }}' class='col-lg-2 control-label'>
                {{ field.label }}
                </label>
                <div class='col-lg-7 '>
                {{ field }}
                </div>
              </div>
            {% endfor %}
            <div class='form-group'>
              <div class='col-lg-10 col-lg-offset-2'>
                <input type='reset' value='{% block 'sm-val' %}
                {% endblock %}' class='btn btn-{% block 'sm-type' %}
                {% endblock %} btn-sm'style='border-radius:0px' />
                <input type='submit' value='{% block 'bg-val' %}
                {% endblock %}' class='btn btn-{% block 'btn-type'%}
                {% endblock %}'style='border-radius:0px' />
              </div>
            </div>
            <a href="{% block 'url' %}
              
            {% endblock %}">
              {% block 'link' %}
              {% endblock %}
            </a>
          </form>
        </div>
        {% block  'warning'%}
        {% endblock %}

    <script type="text/javascript" charset="utf-8">
      $(".close").on('click',function(){
        $(".close").parent().hide();
      });
    </script>
      </div>
    </div>
  </div>
</div>
  </body>
</html>

{# vim: set ts=2 sw=2 sts=2 fdn=4 : #}

controller/templates/controller/front.html
{% extends 'controller/base.html' %}
{% block 'content' %}
{% for one in content  %}
<div class='row'>
    <div class='container'> 
        {{ one.cont | safe }}
    </div>
<div>
    {% endfor %}
{% endblock %}

controller/templates/controller/index.html
{% extends "controller/base.html" %}
{% block 'Title' %}
    Taxi
{% endblock %}

{% block 'content' %}
<div style="height:90%;width:100%">
	<div id="kenburns-slideshow"></div>
	<div id="kenburns-description">
		<h1 id="slide-title" class='text-success'></h1>
	</div>
	<script type="text/javascript" src="static/js/jquery-1.8.2.min.js"></script>
	<script type="text/javascript" src="static/js/kenburns.js"></script>
	
	<script type="text/javascript">
	var titles = ["UB taxi",
				  "Hotel taxi",
				  "VIP taxi korea",
				  "VIP taxi korea",
				  "ABU robocon 2013 unitel 1, 2",
				  "SIT1 & Changes"];

	$(document).ready(function() {
	    $('#kenburns-slideshow').Kenburns({
	    	images: [
	    		"static/images/image6.jpg",
	    		"static/images/image.jpg",
	    		"static/images/vip.jpg",
	    		"static/images/vip1.jpg",
	    		"static/images/image2.jpg",
                "static/images/image7.jpg"
	    	],
	    	scale:0.75,
	    	duration:8000,
	    	fadeSpeed:1200,
	    	ease3d:'cubic-bezier(0.445, 0.050, 0.550, 0.950)',

	    	onSlideComplete: function(){
	    		$('#slide-title').html(titles[this.getSlideIndex()]);
	    	},
	    	onLoadingComplete: function(){
	    		$('#status').html("Loading Complete");
	    	}
	    });
	});
</script>
</div>
{% endblock %}

controller/templates/controller/jslink.html
{% load staticfiles %}
<script src='{% static 'javascripts/libs/jquery.min.js' %}' type='text/javascript' charset='utf-8'>
</script>

<link rel="stylesheet" href="{% static 'css/stylesheets/bootstrap.min.css' %}" title="" type="" />

<script src='{% static 'javascripts/libs/bootstrap.min.js' %}' type='text/javascript' charset='utf-8'>
</script>

<script src='{% static 'javascripts/packed.js' %}' type='text/javascript' charset='utf-8'></script>

<link rel="stylesheet" href="{% static 'css/stylesheets/screen.css' %}" title="" type="" />
	<link rel="stylesheet" type="text/css" href="static/css/stylesheets/style.css">

controller/templates/controller/logon.html
{% extends 'controller/forms.html' %}
{% block 'title' %}
  Нэвтрэх  
{% endblock %}

{% block 'header' %}
  Нэвтрэх  
{% endblock %}

{% block 'sm-type' %}primary{% endblock %}

{% block  'btn-type'%}info{% endblock %}

{% block 'link' %}
  Бүртгүүлэх
{% endblock %}

{% block 'url' %}
register
{% endblock %}

{% block 'sm-val' %}
  Арилгах
{% endblock %}

{% block 'bg-val' %}
  Нэвтрэх
{% endblock %}

controller/templates/controller/map.html
{% extends "controller/base.html" %}
{% block 'Title' %}
    Mongolia Map
{% endblock %}
{% block "somejs" %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="static/css/stylesheets/historyMap.css" type="text/css" media="screen"> 
        <script type="text/javascript" src="static/js/paths/mng.js"></script>
        <script type="text/javascript" src="static/js/historyMap.js"></script>
        <script src="static/js/raphael-min.js" type="text/javascript"></script>
        <script type="text/javascript">
			window.onload = function ()
			{
				historyMapStart();
            };
        </script>
    
{% endblock %}
{% block 'content' %}
	<div id="main_messsage_box" class="modal"
        style="display:none; border-radius: 3px; left:40%; top:5%; width:800px">
		<div id="sehirTakirp" class="modal-header">
			<button type="button" class="close" data-dismiss="modal"  aria-hidden="true">&times;</button>
			<h1 style='color:white'></h1>
		</div>

        <div class="modal-body">
            <p id="main_messsage_box_into" class='text-success'>
            </p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
	</div>
        <div id="canvas">
            <h2 id="mapTitle" style='color:white'>Монгол Улс</h2>
            <div id="paper"></div>
        </div>
{% endblock %}

controller/templates/controller/navbar.html
<div class='navbar navbar-default' style='border-radius:0px'>
 <div class='container'>
    <div class='navbar-header'>
      <a class='navbar-brand'href="{% url 'controller:permission' %}">Easy Taxi Service</a>
    </div>
    <div class='navbar-collapse collapse'>
      <ul class='nav navbar-nav'>
          <li class='dropdown open'>
            <a class='dropdown-toggle' data-toggle='dropdown'href="#"id='drops'>
                Service
            <span class='caret'></span>
            </a>
            <ul class='dropdown-menu' arria-labeledby='drops'>
                <li>
                    <a href="reserve" tabindex='-1'>
                        Reservation
                    </a>
                </li>
                <li>
                    <a href="{% url 'controller:mongolia' %}" tabindex='-1'>
                        Mongolia map
                    </a>
                </li>
            </ul>
            <li>
                <a href="{% url 'controller:news' %}">News</a>
                </li>
            <li>
                <a href="{% url 'controller:feedback'  %}">Feedback</a>
            </li>
          </li>
          <li>
          
          </li>
      </ul>
      <ul class='navbar-nav nav navbar-right'>
        <li><a href='{% url 'controller:logout' %}'>SignOut</a></li>
      </ul>
    </div>
 </div>     
</div>

controller/templates/controller/news.html
{% extends "controller/base.html" %}
{% block 'Title' %}
    News
{% endblock %}
{% block 'content' %}
{% for one in news  %}
<div class='container'>
    <div class='bs-docs-section'>
        <div class='row'>
            <div class='page-header'>
                <div class='col-lg-12'>
                    <h1 class='text-success'>{{ one.header }}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class='jumbotron'>
        <p style="font-size:14px">
        {{ one.text }}
        </p>
    </div>
</div>
{% endfor %}    
{% endblock %}

controller/templates/controller/registration.html
{% extends 'controller/forms.html' %}
{% block 'title' %}
Registration
{% endblock %}

{% block 'header' %}
  Бүртгүүлэх  
{% endblock %}

{% block 'sm-type' %}danger{% endblock %}

{% block  'btn-type'%}success{% endblock %}

{% block 'sm-val' %}
Арилгах
{% endblock %}

{% block 'bg-val' %}
  Бүртлгүүлэх  
{% endblock %}

controller/templates/controller/reservation.html
{% extends 'controller/forms.html' %}
{% block 'title' %}
  Reservation
{% endblock %}

{% block 'header' %}
  Reservation  
{% endblock %}

{% block 'sm-type' %}danger{% endblock %}

{% block  'btn-type'%}success{% endblock %}
{% block 'sm-val' %}
  Clear
{% endblock %}
{% block 'bg-val' %}
  Send Data
{% endblock %}

{% block 'warning' %}
    <div class='col-lg-4'>
       <div class="alert alert-dismissable alert-success">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <strong class='text-danger'>Анхаар</strong></br>
              <p> Манай такси энхий 2 км 1000₮ цааших км 800₮ мөн хүлээлгийн
              мөнгө авахийг анхаарна уу?</p>
        </div> 
    </div>
{% endblock %}

controller/templates/controller/slider.html
{% extends "controller/base.html" %}
{% block 'Title' %}
    Car's
{% endblock %}
http://www.youtube.com/watch?v=R0nkkXkrby0
{% block 'content' %}
    <div class='container'>
        <div class='bs-docs-section'>
            <div class='row'>
                <div class='col-lg-12'>
                    <div class='well'>
                        <div id='left' class='sum'>
                            <img src="static/media/sl.png" class='pos' alt="" />
                        </div>
                        <div id='right' class='sum'>
                            <img src="static/media/sl.png" alt="" />
                        </div>    
                    <img src="static/media/taxi.jpg" id='slider_body'
                    style='margin-left:300px;' />
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}